---
title: "Sports Analytics Resources"
subtitle: "Useful resources"
author: "David Carey"
date: "28 February 2019"
slug: sport-analytics-resources
categories: []
tags: []
description: ''
output:
  html_document:
    toc: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


****************

This document is to collect online resources for teaching sports analytics.







**************
## Auto-grading software

* https://github.com/autolab/Autolab
* https://www.datacamp.com/community/blog/using-datacamp-autograder-teach-r




****************
## Learning R

https://github.com/uc-r/Intro-R

* Good for figures and diagrams
* Good section on importing data and data manipulation


https://moderndive.com/

* Tidyverse
* Hypothesis testing and inference


#### Data Science for Statisticians Workshop

https://github.com/rafalab/ds4stats


### gganimate

https://github.com/thomasp85/gganimate


### ggforce

* Voronoi tesselation
* geom_zoom

https://www.data-imaginist.com/2019/the-ggforce-awakens-again/


****************
## Learning Python

* Python Data Science Handbook - https://github.com/jakevdp/PythonDataScienceHandbook
  * Jupyter notebooks
  * Textbook


### NumPy

https://jalammar.github.io/visual-numpy/



****************
## Sports analytics problems



### Misc

* Full Jose Mourinho Scouting Report on FC Barcelona from 2005/2006:
  - https://twitter.com/PerformanceAna2/status/1106722625470889984?s=19


### Stein's paradox

Patrick Ward Blog post: http://optimumsportsperformance.com/blog/estimating-true-performance/

Baseball paper - Efron and Morris - http://statweb.stanford.edu/~ckirby/brad/other/Article1977.pdf

https://stats.stackexchange.com/questions/304308/why-is-the-james-stein-estimator-called-a-shrinkage-estimator


https://solomonkurz.netlify.com/post/stein-s-paradox-and-what-partial-pooling-can-do-for-you/

* Has R code
* Also does a Bayesian treatment of the baseball problem



### Drafting

#### Lopez - draft efficiency

https://statsbylopez.com/2017/04/25/evaluating-the-evaluators/

Looks at rank correlation of draft order vs. output in leagues and over time.
Could be a good SAP workshop or blog post.



### Player movement

Modeling offensive player movement in professional basketball - https://peerj.com/preprints/3201/
Use this as a SAP workshop





### Expected goals




### Regression to the mean


* Example with AFL goal kicking and fitzRoy: https://analysisofafl.netlify.com/models/2018-06-20-regression-to-the-mean/




### Field equity



### Shot charts


### KPIs

AFL:
https://ricporteous.netlify.com/post/machine-learning-in-afl-part-i-does-the-free-kick-differential-really-matter/


### Result Prediction - tipping models

AFL:

* file:///C:/Users/dcarey/Documents/MEGA/Publications/afl_weighting_schema.pdf
* AFL Lab - SOLDIER Model
    * https://theafllab.wordpress.com/2019/03/02/the-soldier-model/
* AFL Gains
    * https://ricporteous.netlify.com/post/machine-learning-in-afl/#creating-a-machine-learning-model-to-predict-afl-matches
* AFLaytics - A Brownian Motion Inspired ELO Model
    * https://www.aflalytics.com/blog/2019/1/brownian-motion-inspired-elo-model/
* Build an AFL Elo with FitzRoy
    * https://analysisofafl.netlify.com/models/2018-07-23-build-a-quick-elo/
* AFL teams Elo ratings and footy-tipping
    * http://freerangestats.info/blog/2019/03/23/afl-elo







### Soccer passing analysis

Devin Pleuler (Toronto FC) python notebooks on analysing statsbomb passing data: https://github.com/devinpleuler/applied-examples


### NFL play calling

Using NFLscrapR:
https://towardsdatascience.com/nfl-coaches-are-so-so-predictable-3e15fa69bd32
https://github.com/davisj2007/nfl-playcalling/blob/master/nfl-playcalling_script.R




### Benz: "An Examination of Timeout Value, Strategy, and Momentum in NCAA Division 1 Men’s Basketball"

https://github.com/lbenz730/Senior-Thesis

All code for thesis project (R).



**************
## Sports data sets

* Tennis - https://github.com/skoval/deuce
* NRL rugby - https://github.com/fredgj/rugby_scraper
* Rugby - https://github.com/walsh06/python_rugby
* ncaahoopR - https://github.com/lbenz730/ncaahoopR
* statsbomb - soccer - https://github.com/statsbomb/open-data
* NFL - big data bowl - https://github.com/nfl-football-ops/Big-Data-Bowl
* Harvard sports analytics - http://harvardsportsanalysis.org/
* NBA player tracking - https://github.com/PatrickChodowski/NBAr
* Multi-sport - https://github.com/meysubb/Sports_Data_Reference
    * https://github.com/meysubb/Sports_Data_Reference/blob/master/R/Data.md
* Multi-sport - https://github.com/octonion?tab=repositories

#### Player tracking

* STATS - basketball: https://www.stats.com/artificial-intelligence/
* STATS - soccer: https://www.stats.com/artificial-intelligence/


**************
## Sports analytics blogs

AFL

* [The Arc](https://thearcfooty.com/)
* [AFLaytics](https://www.aflalytics.com/)
* [Matter of Stats](http://www.matterofstats.com/)
* [Analysis of AFL](https://analysisofafl.netlify.com/)
  * Same person that made the **fitzRoy** package
* [AFL Lab](https://theafllab.wordpress.com/)
* [AFL Gains](https://ricporteous.netlify.com/)
  * Ric from NSWIS

Tennis

* [Stats On the T]()

**************
## Conference presentations - tutorials - videos




### Sloan Talks

* [DeepQB Deep Learning with Player Tracking to Quantify Quarterback Decision Makin Performance](https://www.youtube.com/watch?v=EeBgUCYhezc)


### Other

* [Andy Andres: "Sabermetrics 101: Introduction to Baseball Analytics" | Talks at Google](https://www.youtube.com/watch?v=wu2twZdrM-E)
* [Skill vs Luck](https://www.youtube.com/watch?v=HNlgISa9Giw&t=71s)

* [FASTER, HIGHER STRONGER? DETERMINING THE EFFECTIVENESS OF SPORTS PERFORMANCE INTERVENTIONS USING BAYESIAN METHODS?](https://uk.humankinetics.com/blogs/british-association-of-sport-and-exercise-sciences-bases-webinars/faster-higher-stronger-determining-the-effectiveness-of-sports-performance-interventions-using-bayesian-methods)


* [Gradient descent, how neural networks learn](https://www.youtube.com/watch?v=IHZwWFHWa-w)



**************
## Sports analytics courses


* https://statsbylopez.com/276labs/
* http://www.pitt.edu/~kpele/moneyballv2.html



**************
## Modelling methods/tutorials


The Theory Behind Overfitting, Cross Validation,
Regularization, Bagging, and Boosting: Tutorial

https://arxiv.org/pdf/1905.12787.pdf


Shiny apps on many concepts: https://sites.psu.edu/shinyapps/category/introductory-apps/statistical-inference/


### Confounding

Statistically Controlling for Confounding Constructs Is Harder than You Think
https://journals.plos.org/plosone/article/file?id=10.1371/journal.pone.0152719&type=printable

* Example of correlation between ice-cream and drowning deaths.
* Shows that if you know the temperature exactly then can control for temp and remove the spurious
correlation.
* Also shows that if you try and use a proxy for temperature (or latent construct) like survey
results for how hot it is on a likert scale then you can't properly control for temperature
and the spurious correlation remains.
* Simulation results show how the risks of false positive results can be **very** high if your
proxy measure is not reliable.
* **Good to make a presentation on this**.







### Linear Regression

http://docs.statwing.com/interpreting-residual-plots-to-improve-your-regression/


#### Log transforms - diagnostics

https://darrendahly.github.io/post/loglog/ (R code and ggplot)


### Mixed effect models

* https://web.stanford.edu/class/psych252/section/Mixed_models_tutorial.html
    * Very good tutorial with R examples and data viz

* https://ourcodingclub.github.io/2017/03/15/mixed-models.html
	* Very good tutorial with R examples and data viz
	
* https://m-clark.github.io/documents.html

* http://m-clark.github.io/posts/2019-05-14-shrinkage-in-mixed-models/
    * Excellent visualisation of parameter estimation and shinkage
    * https://www.tjmahr.com/plotting-partial-pooling-in-mixed-effects-models/








*********************
### Time series

https://resources.rstudio.com/rstudio-conf-2019/melt-the-clock-tidy-time-series-analysis



*********************
### Machine learning


#### Sebastian Raschka Course

https://github.com/rasbt/stat479-machine-learning-fs18


#### Interpretable machine learning

https://christophm.github.io/interpretable-ml-book/





*********************
### Bayesian

https://m-clark.github.io/documents.html

#### Statistical re-thinking

https://github.com/rmcelreath/statrethinking_winter2019

Videos and slides. Uses R code.

(this version uses ggplot and Tidyverse) https://bookdown.org/connect/#/apps/1850/access



#### Fitting GAMs with brms

https://www.fromthebottomoftheheap.net/2018/04/21/fitting-gams-with-brms/


### Multivariate Adaptive Regression Splines
http://uc-r.github.io/mars





*********************
### Hidden Markov Models (HMM)

https://github.com/stevebottos/stevebottos.github.io/blob/master/_downloads/HMM_Tutorial.pdf

http://www.blackarbs.com/blog/introduction-hidden-markov-models-python-networkx-sklearn/2/9/2017




*********************
### Deep Learning

* Dive into deep learning (textbook) - http://d2l.ai/







